require("wardrek.options")
require("wardrek.lazy")
require("wardrek.keymaps")
require("wardrek.highlight_yank")
require("wardrek.remove_trailing_spaces")
require("wardrek.restore_cursor_pos")
require("wardrek.vertical_help")
